robherley/snips.sh

- .github/workflows/db.yml
- internal/db/schema.hcl
- script/atlas
- script/schema-diff
Useful scripts/workflow to detect schema changes.
Hopefully will prevent breaking changes from sneaking in 😄
> Schema diff scripts/workflow

- .github/workflows/image.yml
Will now (correctly) build and tag container image under following conditions:
1. push to main: gets tagged as `sha-123abc`
2. published release: gets tagged as release tag ref
> Update container workflow & fix img tagging

- internal/ssh/handler.go
🤷 oops
s/o @ygelfand for finding it
> [bugfix] prevent double args printed for flags

- web/static/css/index.css
- web/static/js/snips.js
- web/templates/file.go.html
Closes:
- #23 
Instead of listening on a scroll event, use an [intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). It's much more performant and avoids the jittering and unnecessary (not debounced) events of a scroll listener.
Also added a media query to relax the container padding on small screens. 
https://github.com/robherley/snips.sh/assets/16991201/0fe3af6a-e879-4b9c-ad7b-2cf6064f7092
> Fix flickering scroll bug on mobile

- docs/self-hosting.md
- internal/config/config.go
- internal/http/handlers.go
- internal/ssh/constants.go
- internal/ssh/handler.go
Fixes:
- #24 
The problem was that we were calling `program.Quit` and immediately returning. The `program.Quit` send an async message to the bubbletea program to start the quit procedure (that includes resetting the user's terminal). Instead, we'll use `program.Kill` which _immediately_ stops the session and resets the client's terminal settings.
Also made the session limit configurable as `SNIPS_LIMITS_SESSIONDURATION` and exposed on the metadata endpoint.
> Gracefully quit ssh session, make the max duration configurable

- docs/self-hosting.md
- internal/config/config.go
- internal/http/assets.go
- main.go
- web/templates/file.go.html
This allows for additional content in the head (e.g. scripts for analytics)
> Config to extend rendered head element

- .github/workflows/lint.yml
- .github/workflows/test.yml
since they only run on push, the "Approve Workflow" dialog never appears for PRs from first time contributors
oops :)
> Run lint/test workflows on `pull_request` too

- .github/workflows/codeql.yml
Sets up a basic workflow to run CodeQL scan each PR on `ubuntu-latest` to help keep `snips.sh` secure going forward.
> Setup `CodeQL` workflow 

- internal/http/service.go
This is for routes like https://snips.sh/foobar that should 404 instead of rendering the readme.
> Update route handler

- .github/ISSUE_TEMPLATE/01_bug_report.yml
- .github/ISSUE_TEMPLATE/02_feature_request.yml
- .github/ISSUE_TEMPLATE/03_abuse.yml
- README.md
- docs/contributing.md
- Adds contributors to the readme
- Add a contributing guide
- Adds issue templates
> Contributing

- internal/ssh/flags.go
- internal/ssh/flags_test.go
- internal/ssh/handler.go
As specified in #13 , given `-ttl` flag, the upload process will provide user with url link with specified ttl.
Let me know if this is something along that lines of what you were thinking!
Will fail without `-private` flag.
> Allow private upload  with TTL

- web/templates/file.go.html
adds some open graph meta tags to help websites with displaying embed info.
here's how the link of a file looks now when shared on Discord:
> Add basic open graph meta tags

- docs/contributing.md
Reading the documentation, I noticed that the link to `self-hosting.md` links to `selfhosting.md`.
This PR fixes the typo.
> fix self-hosting.md link in contributing.md

- internal/config/config.go
If `SNIPS_SSH_EXTERNAL` is set without specifying a port, implicitly assuming port 22 (`ssh://my.cool.domain` for example), when a file is uploaded, the `ssh` command generated has an empty `-p` arg.
Before fix:
```
> echo hello there | ssh my.cool.domain
Pseudo-terminal will not be allocated because stdin is not a terminal.
┃ File Uploaded 📤
┃ id: m2yrsM1JeY
┃ size: 12 B • type: plaintext • visibility: public
┃ SSH 📠
┃ ssh f:m2yrsM1JeY@my.cool.domain -p
┃ URL 🔗
┃ https://my.cool.domain/f/m2yrsM1JeY
```
After fix:
```
> echo hello there | ssh my.cool.domain
Pseudo-terminal will not be allocated because stdin is not a terminal.
┃ File Uploaded 📤
┃ id: m2yrsM1JeY
┃ size: 12 B • type: plaintext • visibility: public
┃ SSH 📠
┃ ssh f:m2yrsM1JeY@my.cool.domain
┃ URL 🔗
┃ …
```
> [Minor] Fix: Broken ssh command on upload

- script/atlas
- script/install-libtensorflow
- script/lint
- script/record-tape
- script/schema-diff
- script/ssh-tmp
- script/test
There is no reason to prefer `/bin/bash` when none of its unique features are used. Using `/bin/sh` lets you run the script even on those system without `bash` installed (e.g. Alpine Linux, BSD etc)
Also note that using the keyword `function` for function declaration is not standard and you should prefer declare functions by `name()`.
> Make scripts POSIX compliant

- docs/self-hosting.md
- internal/config/config.go
- internal/config/config_test.go
- internal/ssh/middleware.go
- internal/ssh/middleware_test.go
- internal/ssh/service.go
- internal/testutil/file.go
A solution for:
- https://github.com/robherley/snips.sh/issues/43
It adds a new configuration variable, `SNIPS_SSH_AUTHORIZEDKEYSPATH` to point to an `authorized_keys`-like file that will restrict SSH access to the public keys defined in that file. If the envvar is not set, it will behave normally. This is opt-in and will not change default behavior.
> Configuration to restrict SSH access

- .vscode/settings.json
- docs/self-hosting.md
- go.mod
- go.sum
- internal/config/config.go
- internal/db/db_sqlite.go
- internal/db/db_sqlite_test.go
- internal/http/handlers.go
- internal/snips/file.go
- internal/snips/file_test.go
- internal/ssh/handler.go
- internal/tui/views/code/code.go
@robherley
This is a draft pull request that implements file content setter/getter as discussed in #6. I was hoping to get feedback on the core compression and decompression implementations to make sure they align with what you had in mind!
If the implementations are something you had in mind, I'll go ahead and swap `file.Content` statements with getters and setters.
> Compress file content with zstd

- go.mod
- internal/tui/tui.go
- internal/tui/views/prompt/prompt.go
- On small viewports, the signed URL prompt response was not wrapping the text properly
- Fix a panic where a really tiny viewport causes a negative string repeat
> Fix minor TUI bugs

- internal/ssh/flags.go
- internal/ssh/flags_test.go
- internal/timeutil/duration.go
- internal/timeutil/duration_test.go
Closes:
- https://github.com/robherley/snips.sh/issues/65
tl;dr I just yoinked the `time.ParseDuration` from the stdlib and added some more units like `1w` for one week (168 hours) and `1d` for one day (24 hours)
now you can do something like:
```
echo "hello world" | ssh snips.sh -- -private -ttl 1w2d
```
cc @benwaffle
> Support day and week in duration parsing

- internal/renderer/guess.go
- internal/renderer/guess_amd64.go
This allow users to build the app without the guesser (and tensorflow) even on amd64 platforms, just using the `-tags noguesser` when building.
It would though gets panic when using with `SNIPS_ENABLEGUESSER=True`. But I guess its fine.
> Disable guesser using build tags

- web/static/js/snips.js
This is related to issue #175 but I also did some more work, sorry I couldnt resist 😇
- changed a little the `getSelectedLines`:
`location.hash` will always return string so no need the optional channing
- changed a little the `highlightLines`:
`getSelectedLines` will always return array and already check the `location.hash` before so I replaced that if and add some deconstruct assignment, just small changes to reduce some lines
- changed the `setAttribute/removeAttribute` for `toggleAttribute` with force parameter, just small change to reduce some lines
- added a new method `scrollToLine` to scroll to the highlighted lines
it unfortunatelly "needs" the `setTimeout` in order to always get fired, otherwise it will only works for a new page load (not for refresh). It does works better …
> Add scroll to highlighted lines

- go.mod
- go.sum
- internal/http/assets.go
- internal/http/handlers.go
- internal/http/middleware.go
- internal/http/service.go
- internal/http/service_test.go
With the routing enhancements introduced in go 1.22:
- https://go.dev/blog/routing-enhancements
We no longer need a separate router dependency, and can rely on the standard library.
Related, the metric `path` is no longer emitted, and instead it's `pattern`.
> Use `net/http` router instead of `chi`
